name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # 20.04 yerine 22.04 daha güncel ve stabil

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Setup Java (OpenJDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        # Kırık paketleri düzeltmek ve eksik bağımlılığı (libunwind-dev) zorla yüklemek için:
        sudo apt-get install -y --fix-broken
        sudo apt-get install -y libunwind-dev
        sudo apt-get install -y \
          build-essential \
          git \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libgstreamer-plugins-base1.0-dev \
          zip \
          unzip \
          autoconf \
          libtool \
          pkg-config \
          libncurses5-dev \
          libncursesw5-dev \
          libffi-dev \
          libssl-dev \
          cmake

    - name: Install Python tools
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade "cython<3.0"
        pip install buildozer

    - name: Build APK
      run: |
        # Lisansları kabul et ve derlemeyi başlat
        export APP_ANDROID_ACCEPT_SDK_LICENSE="1"
        buildozer -v android debug
      env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: deprem-app-debug
        path: bin/*.apk
